version: '3'

services:
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gorm
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # media:
  #   build:
  #     context: ./media
  #     dockerfile: dockerfile
  #   ports:
  #     - "7070:7070"
  #     - "7071:7071"
  #   depends_on:
  #     - server

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
  # web:
  #   build:
  #     context: ./vreel
  #     dockerfile: dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server
  #   restart: always
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
