version: "3"

services:
  db:
    image: "postgres:latest"
    ports:
      - 5440:5432
    environment:
      - POSTGRES_DB=gorm
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  mediaDb:
    image: "postgres:latest"
    ports:
      - 5441:5432
    environment:
      - POSTGRES_DB=gorm
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
    volumes:
      - ./pgdata1:/var/lib/postgresql/data

  # media:
  #   build:
  #     context: ./HLS-Server
  #     dockerfile: dockerfile
  #   network_mode: "host"
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./hls_volume

  #   depends_on:
  #     - server
  #   environment:
  #     - DB_HOST=db

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: dockerfile
  #   network_mode: "host"
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
