// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID          string   `json:"ID"`
	Author      string   `json:"author"`
	Name        string   `json:"name"`
	Thumbnail   string   `json:"thumbnail"`
	StartTime   string   `json:"start_time"`
	EndTime     string   `json:"end_time"`
	Description string   `json:"description"`
	Location    string   `json:"location"`
	GroupID     string   `json:"group_id"`
	Repeat      string   `json:"repeat"`
	Link        string   `json:"link"`
	Groups      []string `json:"groups"`
}

type Group struct {
	ID          string   `json:"id"`
	Author      string   `json:"author"`
	Name        string   `json:"name"`
	Location    string   `json:"location"`
	MeetTimes   []string `json:"meet_times"`
	Private     bool     `json:"private"`
	ParentGroup string   `json:"parent_group"`
	ChildGroups []*Group `json:"child_groups"`
	Members     []string `json:"members"`
	Events      []*Event `json:"events"`
	Vreel       *Vreel   `json:"vreel"`
}

type LocalSession struct {
	Token string `json:"token"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MutationResponse struct {
	Succeeded bool   `json:"succeeded"`
	Message   string `json:"message"`
}

type NewEvent struct {
	Name        string   `json:"name"`
	Thumbnail   string   `json:"thumbnail"`
	StartTime   string   `json:"start_time"`
	EndTime     string   `json:"end_time"`
	Description string   `json:"description"`
	Location    string   `json:"location"`
	GroupID     string   `json:"group_id"`
	Repeat      string   `json:"repeat"`
	Link        string   `json:"link"`
	Groups      []string `json:"groups"`
}

type NewGroup struct {
	Token       string   `json:"token"`
	Name        string   `json:"name"`
	Location    string   `json:"location"`
	MeetTimes   []string `json:"meet_times"`
	Private     bool     `json:"private"`
	ParentGroup string   `json:"parent_group"`
}

type NewSlide struct {
	ContentType   string `json:"content_type"`
	URI           string `json:"uri"`
	SlideLocation int    `json:"slide_location"`
}

type NewUser struct {
	Username        string  `json:"username"`
	FirstName       *string `json:"first_name"`
	LastName        *string `json:"last_name"`
	Email           string  `json:"email"`
	PhoneNumber     *string `json:"phone_number"`
	Password        string  `json:"password"`
	BusinessAddress *string `json:"business_address"`
	BillingAddress  *string `json:"billing_address"`
	Website         *string `json:"website"`
	JobTitle        *string `json:"job_title"`
}

type ResetPasswordInput struct {
	Email string `json:"email"`
}

type ResetPasswordResponse struct {
	Message     string `json:"message"`
	EmailExists bool   `json:"email_exists"`
	ResetToken  string `json:"reset_token"`
}

type ResolvedPasswordReset struct {
	Message   string `json:"message"`
	Succeeded bool   `json:"succeeded"`
}

type Slide struct {
	ID            string         `json:"id"`
	ContentType   string         `json:"content_type"`
	URI           string         `json:"uri"`
	SlideLocation int            `json:"slide_location"`
	Metadata      *SlideMetaData `json:"metadata"`
}

type SlideMetaData struct {
	Created string `json:"created"`
	Size    string `json:"size"`
}

type User struct {
	ID              string   `json:"id"`
	Username        string   `json:"username"`
	FirstName       string   `json:"first_name"`
	LastName        string   `json:"last_name"`
	Email           string   `json:"email"`
	PhoneNumber     string   `json:"phone_number"`
	Password        string   `json:"password"`
	BusinessAddress string   `json:"business_address"`
	BillingAddress  string   `json:"billing_address"`
	Website         string   `json:"website"`
	JobTitle        string   `json:"job_title"`
	Groups          []*Group `json:"groups"`
	Vreel           *Vreel   `json:"vreel"`
}

type Vreel struct {
	Author    string   `json:"author"`
	PageTitle string   `json:"page_title"`
	ButtonURI *string  `json:"button_uri"`
	Slides    []*Slide `json:"slides"`
}
